### ISSUE TITLE
Error message returned to client socket gets modified

### ISSUE THREAD

**Issue by vartanbeno** [PlayNetwork/json-ipc-lib#14]
https://github.com/PlayNetwork/json-ipc-lib/blob/944638fc0bdfabcec39f502c56fbeecd3e419ada/src/Client.js#L152-L154

When returning an error to the client socket, the error message gets prepended a `JSON-IPC Client Exception::` string to it. This causes some issues, such as if our error message is a stringified JSON object that's meant to be parsed via JavaScript's `JSON` class.

**Comment by brozeph** [comment]
If the extra colon is removed, will this work with your use case, or is the message wrap the problem?

**Comment by vartanbeno** [comment]
> If the extra colon is removed, will this work with your use case, or is the message wrap the problem?

It's the message wrap that's the problem. Say we want to send the following to the client:

```
{"code":"SOME_ERROR","message":"An error occurred."}
```

This is what gets sent:

```
JSON-IPC Client Exception::{"code":"SOME_ERROR","message":"An error occurred."}
```
